"""entries table

Revision ID: dbdaab58936b
Revises: 58d40ff9c4e4
Create Date: 2018-03-26 16:38:44.735000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdaab58936b'
down_revision = '58d40ff9c4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('type', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_entry_type'), 'entry', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_type'), table_name='entry')
    op.drop_column('entry', 'type')
    # ### end Alembic commands ###
